### PR TITLE
fix: align backgroundRotation validation with DiceBear v9 API

### LINKED ISSUE #44: Recheck documentation of HTTP API for options
Make sure all options are available in the package. See [options](https://www.dicebear.com/how-to-use/http-api/#options)

### PR DESCRIPTION
**Pull request by Deepak8858**
According to the DiceBear v9 documentation, backgroundRotation can accept a range (min, max) or a single value. This PR updates the validation logic to allow 1 or 2 values and ensures rotation is within the 0-360 range.

Closes #44

### CODE REVIEW

File: lib/dice_bear.dart [hunk 1]
```diff
@@ -360,17 +360,17 @@ class DiceBearCoreOptions {
...
           'backgroundRotation',
-          'must contain exactly 2 values [min, max]',
+          'must contain 1 or 2 values [min, max] or [value]',
         );
       }
 
       for (final value in backgroundRotation!) {
         _checkRange(
-            name: 'backgroundRotation', value: value, min: -360, max: 360);
+            name: 'backgroundRotation', value: value, min: 0, max: 360);
```
Comment (ZaifSenpai) [inline lib/dice_bear.dart]: The gradient rotation range is from -360 to 360 according to the [documentation](https://www.dicebear.com/how-to-use/js-library/#core-options:~:text=backgroundRotation,360%20to%20360)).
Thank you
